name: Build and Release

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1 
          
      - name: Initialize Submodules Manually
        run: |
          git submodule init
          git submodule update --depth 1 --exclude ponio_android_controller

      - name: Set up Compiler and Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libevdev-dev

      - name: Build with Makefile
        run: make

      - name: Get commit messages
        id: get_commits
        run: |
          COMMITS=$(git log --oneline $(git describe --tags --abbrev=0)..HEAD)
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          echo "$COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        run: |
          VERSION=$(date +'%Y%m%d%H%M')  # Create a version based on current date/time
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          gh release create "$VERSION" ./build/ponio --title "$VERSION" --notes "${{ env.COMMITS }}"

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ env.VERSION }}
          files: ./build/ponio
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
