name: Build and Release

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1 
          
      - name: Initialize Submodules Manually
        run: |
          git submodule init
          git submodule update --depth=1

      - name: Set up Compiler and Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
                                  libevdev-dev \
                                  libasound2-dev \
                                  libx11-dev \
                                  libxrandr-dev \
                                  libxi-dev \
                                  libgl1-mesa-dev \
                                  libglu1-mesa-dev \
                                  libxcursor-dev \
                                  libxinerama-dev \
                                  libwayland-dev \
                                  libxkbcommon-dev
          cd lib/raylib/src/ && make && cd ../../../  

      - name: Build with Makefile
        run: make

      - name: Get commit messages
        id: get_commits
        run: |
          COMMITS=$(git log --oneline $(git describe --tags --abbrev=0)..HEAD)
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          echo "$COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Version Tag
        id: create_tag
        run: |
          VERSION=$(echo Fresh Air $(date +'%m/%Y %H:%M'))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git tag "$VERSION"  # Create a tag with the version
          git push origin "$VERSION"  # Push the tag to the repository

      - name: Create Release
        id: create_release
        run: |
          gh release create "$VERSION" ./build/ponio --title "$VERSION" --notes "${{ env.COMMITS }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }} 
          files: ./build/ponio
          token: ${{ secrets.GITHUB_TOKEN }} 
